#!/bin/bash

LD_LIBRARY_PATH=$XILINX_ISE_ROOT/ISE/lib/lin:$XILINX_ISE_ROOT/EDK/lib/lin:$XILINX_ISE_ROOT/common/lib/lin
PATH=$XILINX_ISE_ROOT/ISE/bin/lin:$XILINX_ISE_ROOT/ISE/sysgen/util:$XILINX_ISE_ROOT/ISE/../../../DocNav:$XILINX_ISE_ROOT/PlanAhead/bin:$XILINX_ISE_ROOT/EDK/bin/lin:$XILINX_ISE_ROOT/EDK/gnu/microblaze/lin/bin:$XILINX_ISE_ROOT/EDK/gnu/powerpc-eabi/lin/bin:$XILINX_ISE_ROOT/EDK/gnu/arm/lin/bin:$XILINX_ISE_ROOT/EDK/gnu/microblaze/linux_toolchain/lin32_be/bin:$XILINX_ISE_ROOT/EDK/gnu/microblaze/linux_toolchain/lin32_le/bin:$XILINX_ISE_ROOT/common/bin/lin:$PATH

echo >&2 "$@"
exec "$@"
